### ISSUE TITLE
Issue refreshing markers 

### ISSUE THREAD

**Issue by daschewie** [googlemaps/android-maps-utils#63] opened 2014-02-27 18:25 UTC
I am trying to change the icon for a selected marker. Neither calling ClusterManager.cluster, nor MapView.invalidate will cause the ClusterRenderer to render new pins.

``` Java
protected void onBeforeClusterItemRendered(FacilityClusterItem item, MarkerOptions markerOptions) {
        Facility facility = item.getFacility();

        int pinId = 0;

        if (TextUtils.equals(facility.getId(), mSelectedFacilityId)) {
            mIconGenerator.setBackground(mContext.getResources().getDrawable(R.drawable.map_pin_white));
            pinId = facility.getFacilityType().getSelectedMapPinId();
        } else {
            mIconGenerator.setBackground(mContext.getResources().getDrawable(R.drawable.map_pin_purple));
            pinId = facility.getFacilityType().getMapPinId();
        }

        icon = BitmapDescriptorFactory.fromResource(pinId);
        markerOptions.icon(icon);
    }
```

**Comment by hermannloose** [comment] 2015-02-12 16:52
@jakeonrails You can theoretically override [`onClusterItemRendered`](https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/clustering/view/DefaultClusterRenderer.java#L721) to achieve this, which allows you to set the icon on the existing `Marker` instead of `MarkerOptions`. The gotcha with this approach is that the call happens as part of [`CreateMarkerTask#perform`](https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/clustering/view/DefaultClusterRenderer.java#L809) which should run as part of the `RenderTask`; only the latter [does not actually do anything](https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/clustering/view/DefaultClusterRenderer.java#L335) if the sets of clusters did not change, according to `equals`. Now, this should be fine if you're diligent in overriding `equals` for your class implementing `ClusterItem`, only `ClusterManager#setAlgorithm` decides that it will slap a `PreCachingAlgorithmDecorator` on whatever you pass in (not that you asked for it), so that as far as I can see you cannot ever hope to convince the renderer that yes, in fact your clusters have changed ...

So what I think we really want is for `ClusterManager` to not try and be too clever about enhancing the algorithm you pass in, if the decorator actually breaks behaviour.

**Comment by DarekDeo** [comment] 2016-01-22 10:45
java.lang.IllegalArgumentException: Released unknown imageData reference
                                                                           at com.google.a.a.ae.a(Unknown Source)
                                                                           at com.google.maps.api.android.lib6.e.dn.c(Unknown Source)
                                                                           at com.google.maps.api.android.lib6.e.ag.o(Unknown Source)
                                                                           at com.google.maps.api.android.lib6.e.ag.a(Unknown Source)
                                                                           at com.google.android.gms.maps.model.a.p.onTransact(SourceFile:51)
                                                                           at android.os.Binder.transact(Binder.java:380)
                                                                           at com.google.android.gms.maps.model.internal.zzf$zza$zza.remove(Unknown Source)
                                                                           at com.google.android.gms.maps.model.Marker.remove(Unknown Source)
                                                                           at com.google.maps.android.MarkerManager$Collection.remove(MarkerManager.java:163)
                                                                           at com.google.maps.android.MarkerManager.remove(MarkerManager.java:140)
                                                                           at com.google.maps.android.clustering.view.DefaultClusterRenderer$AnimationTask.onAnimationEnd(DefaultClusterRenderer.java:912)
                                                                           at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1089)
                                                                           at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:666)
                                                                           at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5297)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

Getting above error while using onClusterItemRendered. I am running async task to get image for marker:
```java
protected void onClusterItemRendered(final Poi clusterItem, final Marker marker) {
    super.onClusterItemRendered(clusterItem, marker);

    try {
        URL url = new URL(clusterItem.getImage());
        AsyncDownloadImage async = new AsyncDownloadImage(marker);
        async.execute(url);
    } catch (MalformedURLException e) {
        Log.e("CluserRenderer", "Wrong url address: " + clusterItem.getImage());
    }
}
```

And in onPostExecute I do this (markerReference is WeakReference):
```java
protected void onPostExecute(final Bitmap bitmap) {

    Marker marker = markerReference.get();

    if (bitmap != null && marker != null) {
        mImageView.setImageBitmap(bitmap);
        Bitmap icon = mIconGenerator.makeIcon();
        try {
            marker.setIcon(BitmapDescriptorFactory.fromBitmap(icon));
        } catch (IllegalArgumentException e) {
            Log.e("ClusterRenderer", "Couldn't set icon.");
        }
    }
}
```

Images for marker cluster items do render while zooming in, then while zooming out the cluster group is rendered for marker, then again while zooming in items do render correctly. Exception occurs when user do zoom in and zoom out fast when items did not render yet.

**Comment by DarekDeo** [comment] 2016-01-22 13:39
Keeping marker object instead of weakreference fixed issue for me. Additionaly I keep hashmap of already downloaded url/ bitmap. Whenever clusteritem gets rendered it checks hashmap for bitmaps.

**Comment by DarekDeo** [comment] 2016-01-25 14:55
Nope, still crashes, same error as before.

**Comment by ShawnDuan** [comment] 2016-03-03 22:42
+1

**Comment by Jogan** [comment] 2016-03-24 15:36
Currently working on same issue hopefully can figure something out.

**Comment by stephenmcbride** [comment] 2016-05-02 04:27
I managed to get this working for showing a selected state on a marker. It requires extending the DefaultClusterRenderer class and overriding one method (onBeforeClusterItemRendered) and adding an onClusterItemClick listener.

    public class MyCustomRenderer<T> extends DefaultClusterRenderer implements ClusterManager.OnClusterItemClickListener<MyClusterItem> {

    private MyClusterItem currentClickedClusterItem;

    public MyCustomRenderer(Context context, GoogleMap map, ClusterManager<MyClusterItem> clusterManager) {
        super(context, map, clusterManager);
        setOnClusterItemClickListener(this);
    }

    @Override
    protected void onBeforeClusterItemRendered(ClusterItem item, MarkerOptions markerOptions) {
        if (currentClickedClusterItem != null && item.equals(currentClickedClusterItem)) {
            markerOptions.icon(BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_BLUE));
        } else {
            markerOptions.icon(BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_RED));
        }
        
    }

    @Override
    public boolean onClusterItemClick(MyClusterItem item) {

        if (currentClickedClusterItem != null) {
            getMarker(currentClickedStopItem).setIcon(BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_RED));
        }
        currentClickedStopItem = item;
        getMarker(item).setIcon(BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_BLUE));
        return true;
    }
    }

**Comment by rohanagarwal94** [comment] 2017-07-12 20:43
@stephenmcbride your code is not working. Any update on this?

**Comment by bosung90** [comment] 2017-07-25 22:33
@stephenmcbride Thank you!!!!!!

**Comment by SimonHaenle2** [comment] 2019-06-04 14:42
getMarker() always returns null for me, no way to get this working...

**Comment by arriolac** [comment] 2020-01-29 22:50
Duplicate of #90, closing this issue in favor of that one instead. See the discussion there for possible workarounds in the meantime.

**Closed by arriolac** 2020-01-29 22:50 UTC
Labels: triage me
