### ISSUE TITLE
ClusterItem and ClusterManager breaks in compile when upgrading from 1.0.0 to 1.0.1

### ISSUE THREAD

**Issue by RoarGronmo** [googlemaps/android-maps-utils#671] opened 2020-03-19 20:51 UTC
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ**

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response.

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/).

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
2. OS type and version
3. Library version and other environment information

#### Steps to reproduce

  1. ?

#### Code example

```
# example
```

#### Stack trace
```
# example
```

Following these steps will guarantee the quickest resolution possible.

Thanks!

----

Following is not reachable after upgrading the 
com.google.maps.android:android-maps-utils:1.0.0
to 
com.google.maps.android:android-maps-utils:1.0.1

import com.google.maps.android.clustering.ClusterItem
import com.google.maps.android.clustering.ClusterManager

what breaking changes did you do ?

RG

**Comment by barbeau** [comment] 2020-03-19 21:00
@RoarGronmo Thanks for the report! I believe this is a duplicate of https://github.com/googlemaps/android-maps-utils/issues/668. We're aware of the issue and plan to release v1.0.2 shortly which should hopefully fix this issue. I'm going to close this issue as we've already merged a fix for https://github.com/googlemaps/android-maps-utils/issues/668, but we will revisit if we continue to see problems.

**Closed by barbeau** 2020-03-19 21:00 UTC
Labels: triage me, type: bug
