### ISSUE TITLE
HEATMAPS WITH PLACES API search function error

### ISSUE THREAD

**Issue by habib-m-ahmed** [googlemaps/android-maps-utils#770] opened 2020-08-04 17:07 UTC
When I enter a location into the "HEATMAPS WITH PLACES API" demo, the app crashes and it gives the following message: "Unfortunately, Maps Utils Demo has stopped". The heatmap itself is not showing up either.

However, in the other "HEATMAPS DEMO ACTIVITY" the heatmap itself shows and all the other features (radius, gradient, etc) work completely fine. 

I created the secure.properties file and put my API key in the specified spot. I also entered my API key in the HeatMapsPlacesDemoActivity file where it says to. 

The device I am using is Moto G (3rd gen) and it is running android version 6.0.

I have not edited any files except adding in the secure.properties file and putting in my API key into the HeatMapsPlacesDemoActivity file as mentioned above. 

This is what the LogCat looks like once I enter in "Sydney" into the search bar and then click the "GO" button:

08-04 13:01:59.762 28667-28667/? I/art: Late-enabling -Xcheck:jni
08-04 13:01:59.854 28667-28667/com.google.maps.android.utils.demo W/System: ClassLoader referenced unknown path: /data/app/com.google.maps.android.utils.demo-2/lib/arm
08-04 13:01:59.903 28667-28667/com.google.maps.android.utils.demo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
08-04 13:01:59.950 28667-28667/com.google.maps.android.utils.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
08-04 13:01:59.950 28667-28667/com.google.maps.android.utils.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
08-04 13:02:00.111 28667-28689/com.google.maps.android.utils.demo D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-04 13:02:00.228 28667-28689/com.google.maps.android.utils.demo I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (I14a17c7611)
    OpenGL ES Shader Compiler Version: XE031.06.00.02
    Build Date: 12/04/15 Fri
    Local Branch: workspace
    Remote Branch: 
    Local Patches: 
    Reconstruct Branch: 
08-04 13:02:00.229 28667-28689/com.google.maps.android.utils.demo I/OpenGLRenderer: Initialized EGL, version 1.4
08-04 13:02:14.677 28667-28667/com.google.maps.android.utils.demo I/zzbz: Making Creator dynamically
08-04 13:02:14.690 28667-28667/com.google.maps.android.utils.demo I/DynamiteModule: Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:202414000
08-04 13:02:14.690 28667-28667/com.google.maps.android.utils.demo I/DynamiteModule: Selected remote version of com.google.android.gms.maps_dynamite, version >= 202414000
08-04 13:02:14.690 28667-28667/com.google.maps.android.utils.demo V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
08-04 13:02:14.737 28667-28667/com.google.maps.android.utils.demo W/System: ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000001c/n/armeabi-v7a
08-04 13:02:14.737 28667-28667/com.google.maps.android.utils.demo W/System: ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000001c/n/armeabi
08-04 13:02:14.826 28667-28667/com.google.maps.android.utils.demo I/Google Maps Android API: Google Play services client version: 12451000
08-04 13:02:14.847 28667-28667/com.google.maps.android.utils.demo I/Google Maps Android API: Google Play services package version: 202414017
08-04 13:02:15.415 28667-28667/com.google.maps.android.utils.demo I/Choreographer: Skipped 54 frames!  The application may be doing too much work on its main thread.
08-04 13:02:17.401 28667-29099/com.google.maps.android.utils.demo W/DynamiteModule: Local module descriptor class for com.google.android.gms.googlecertificates not found.
08-04 13:02:17.432 28667-29099/com.google.maps.android.utils.demo I/DynamiteModule: Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
08-04 13:02:17.432 28667-29099/com.google.maps.android.utils.demo I/DynamiteModule: Selected remote version of com.google.android.gms.googlecertificates, version >= 4
08-04 13:02:17.451 28667-29099/com.google.maps.android.utils.demo W/System: ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000001b/n/armeabi-v7a
08-04 13:02:17.451 28667-29099/com.google.maps.android.utils.demo W/System: ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000001b/n/armeabi
08-04 13:02:32.675 28667-28678/com.google.maps.android.utils.demo I/art: Background partial concurrent mark sweep GC freed 15093(884KB) AllocSpace objects, 9(2MB) LOS objects, 25% free, 11MB/15MB, paused 8.373ms total 33.827ms

**_### **************THIS IS WHERE THE ERROR STARTS**************_**

08-04 13:02:32.786 28667-29149/com.google.maps.android.utils.demo E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
    Process: com.google.maps.android.utils.demo, PID: 28667
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:200)
        at android.os.Handler.<init>(Handler.java:114)
        at android.widget.Toast$TN.<init>(Toast.java:345)
        at android.widget.Toast.<init>(Toast.java:101)
        at android.widget.Toast.makeText(Toast.java:259)
        at com.google.maps.android.utils.demo.HeatmapsPlacesDemoActivity.getJsonPlaces(HeatmapsPlacesDemoActivity.java:265)
        at com.google.maps.android.utils.demo.HeatmapsPlacesDemoActivity.getPoints(HeatmapsPlacesDemoActivity.java:210)
        at com.google.maps.android.utils.demo.HeatmapsPlacesDemoActivity.access$200(HeatmapsPlacesDemoActivity.java:60)
        at com.google.maps.android.utils.demo.HeatmapsPlacesDemoActivity$MakeOverlayTask.doInBackground(HeatmapsPlacesDemoActivity.java:305)
        at com.google.maps.android.utils.demo.HeatmapsPlacesDemoActivity$MakeOverlayTask.doInBackground(HeatmapsPlacesDemoActivity.java:303)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
08-04 13:02:32.950 28667-28667/com.google.maps.android.utils.demo W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
08-04 13:02:33.028 28667-28689/com.google.maps.android.utils.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb9fc5898
08-04 13:02:33.028 28667-28689/com.google.maps.android.utils.demo D/OpenGLRenderer: endAllActiveAnimators on 0xb8ebeee8 (RippleDrawable) with handle 0xba042e70
08-04 13:02:33.037 28667-28667/com.google.maps.android.utils.demo W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
08-04 13:02:33.037 28667-28667/com.google.maps.android.utils.demo W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
08-04 13:02:56.876 28667-29149/com.google.maps.android.utils.demo I/Process: Sending signal. PID: 28667 SIG: 9

Thanks for your help!

**Comment by barbeau** [comment] 2020-08-04 19:31
Thanks @habib-m-ahmed. I can confirm I see the same behavior when running on a Samsung Galaxy S8+ with Android 9.0 when I use my own Places API key.

Looks like there are a few things going wrong here. The crash is because there is an IOException when trying to call the Places API in `getJsonPlaces()`, and then in the catch block the app is trying to show a `Toast` from the background thread. So that needs to be fixed.

And, it looks like the Places API call is failing because "radar search" was deprecated a while back:
https://cloud.google.com/blog/products/maps-platform/announcing-deprecation-of-place-add

Looks like Nearby Search can work for our purposes here. I just opened PR https://github.com/googlemaps/android-maps-utils/pull/771 which has a fix for these problems. You can try that out in the meantime, or wait for it to be merged. Let me know if it works for you!

**Comment by habib-m-ahmed** [comment] 2020-08-04 21:27
The app is not crashing anymore, however, the heatmap still isn't showing and the following message gets displayed every time I put something in the search bar: "No results for this query :(". 

Is there something I am still missing?

**Comment by barbeau** [comment] 2020-08-04 22:23
@habib-m-ahmed I typed "pizza" in the input box, and that returned results for me. It's searching for places near Sydney, Australia, so you'll need to use a generic search term that would work there. Does "pizza" work for you?

**Comment by habib-m-ahmed** [comment] 2020-08-04 22:26
I tried "pizza" and it still says "No results for this query :(". Is the heatmap working on your end?

**Closed** 2020-08-04 22:25 UTC
Labels: priority: p2, type: bug

**Comment by barbeau** [comment] 2020-08-04 22:33
Yes, it works:

![image](https://user-images.githubusercontent.com/928045/89351895-ed15ac80-d680-11ea-853c-dfcf81de25d5.png)

Did you enable the Places API in the Google Cloud API console?

I added some debug log output as well, so it should output the API URL being used in the request now too to Logcat. You can try clicking on that URL to open in your browser to make sure you're getting a valid API response.

**Comment by habib-m-ahmed** [comment] 2020-08-04 22:45
Yes, I enabled the Places API in the API console. 

I'm not sure if I am getting the API URL in the Logcat, can you please further specify where I can find it in case I am just looking over it?

**Comment by habib-m-ahmed** [comment] 2020-08-04 22:55
Ignore that last comment, I got it to work! 

All I did was generate a new API key and it started working for some reason..

Thanks so much for your help, I really appreciate it :)

**Comment by barbeau** [comment] 2020-08-05 13:33
@habib-m-ahmed Glad to hear it's working, you're welcome!
