### ISSUE TITLE
Can't build the project after I integrated the utils

### ISSUE THREAD

**Issue by calvinchankf** [googlemaps/android-maps-utils#249] opened 2016-02-24 03:39 UTC
Actually several days ago, it worked. But today it fails...

Full error message:

Error:Execution failed for task ':app:transformClassesWithDexForDebug'. > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: finished with non-zero exit value 2

Then I googled around and tried
defaultConfig {
  multiDexEnabled true
}
It can build successfully but it crashes when I use the library
e.g. when I customize markers, then i will get the error like this
FATAL EXCEPTION: main java.lang.NoClassDefFoundError:com.google.maps.android.ui.BubbleDrawable

Actually, I also tried clean project, rebuild project, restart android studio, uninstall app, but no luck

P.S.
i integrated the library with gradle like this
dependencies {
  compile 'com.google.maps.android:android-maps-utils:0.4+'
}

**Comment by calvinchankf** [comment] 2016-02-27 08:36
any update?

**Comment by markmcd** [comment] 2016-03-03 03:13
Dupe of #248

**Closed by markmcd** 2016-03-03 03:13 UTC
