### ISSUE TITLE
Disappearing clusters...

### ISSUE THREAD

**Issue by KennyGoers** [googlemaps/android-maps-utils#288] opened 2016-06-15 17:09 UTC
I keep losing marker clusters when zooming out, they eventually come back but only from zooming, here is an example of what I'm talking about, notice the blank squares.

![screenshot_20160615-120505](https://cloud.githubusercontent.com/assets/429628/16089685/e638d3d8-32f1-11e6-93ba-08d39db6410d.png)

I'm doing custom markers, but that is it as far as customization of the clustering goes.

**Comment by bkenn011** [comment] 2016-06-15 17:36
Also happening for me as well, and I've seen other mentions in the issues list for this project about this and version 0.4.3.  Actually just came back here after seeing it again in my app and hoping for a new version, but seems like it's still a thing and 0.4.3 remains the latest.

**Comment by barbeau** [comment] 2016-06-15 20:10
This looks like a duplicate of https://github.com/googlemaps/android-maps-utils/issues/276.  This is caused by a bug in Google Play Services, and it appears to be fixed with Google Play Services `9.2.56` being installed on the device - https://code.google.com/p/gmaps-api-issues/issues/detail?id=9765#c69.

So the user needs to update Google Play Services to `9.2.56` on their device to resolve this - note that it's being rolled out in stages, so the update may not be available yet to all users.

**Closed** 2016-06-15 20:45 UTC
