### ISSUE TITLE
NullPointerException on removing item from ClusterManager with NonHierarchicalDistanceBasedAlgorithm when there are more than 1000 items.

### ISSUE THREAD

**Issue by giacomodeglinnocenti** [googlemaps/android-maps-utils#348] opened 2017-01-19 14:52 UTC
**Summary:** 

NullPointerException on removing item from ClusterManager with NonHierarchicalDistanceBasedAlgorithm when there are more than 1000 items.

**Steps to reproduce:** 

Add 1000 items.
Remove 1 item.

**Expected behavior:** 

Remove the item.

**Observed behavior:** 

Crash. NPE.

**Device and Android version:** 

Android L,M.

**Screenshots:** 

```
  E/UncaughtException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.remove(java.lang.Object)' on a null object reference
        at com.google.maps.android.quadtree.PointQuadTree.remove(PointQuadTree.java:176)
        at com.google.maps.android.quadtree.PointQuadTree.remove(PointQuadTree.java:171)
        at com.google.maps.android.quadtree.PointQuadTree.remove(PointQuadTree.java:153)
        at com.google.maps.android.clustering.algo.NonHierarchicalDistanceBasedAlgorithm.removeItem(NonHierarchicalDistanceBasedAlgorithm.java:95)
        at com.google.maps.android.clustering.algo.PreCachingAlgorithmDecorator.removeItem(PreCachingAlgorithmDecorator.java:61)
        at com.google.maps.android.clustering.ClusterManager.removeItem(ClusterManager.java:161)
        at com.giacomodeglinnocenti.myApp.controllers.MapClusterManager.removeItem(MapClusterManager.java:72)
```

**It is possible this is a duplicate of #308 ? In case I see that the guy there fixed the issue via PR.. But maybe the code has not been added to maven? **

I'm using the following dependency:

`compile 'com.google.maps.android:android-maps-utils:0.4.+'`

**Comment by barbeau** [comment] 2017-01-19 17:36
@giacomodeglinnocenti Yes, I believe this is a duplicate of https://github.com/googlemaps/android-maps-utils/issues/308, which has been fixed in the master branch.  This fix hasn't been released yet, but I'll go ahead and close this as the problem has been resolved.

@stephenmcd would you be able to cut a new release from the master branch?

**Closed by barbeau** 2017-01-19 17:36 UTC
Labels: bug, duplicate

**Comment by giacomodeglinnocenti** [comment] 2017-01-19 21:38
Ok, thank you @barbeau , I hope you or @stephenmcd will release soon!

**Comment by stephenmcd** [comment] 2017-01-19 22:28
We're almost ready to merge a large refactor of KML/GeoJSON internals, probably some time over the next week or so. Once that's done we'll be pushing a new release.

**Comment by giacomodeglinnocenti** [comment] 2017-01-20 11:09
Ok, thank you @stephenmcd . I'll wait for that.

**Comment by barbeau** [comment] 2021-10-20 20:35
@natansalda Could you open a new issue for this? It looks like a different issue - looking at the stack trace it seems like the null reference is in `AcceptancePoint.hashCode()`, which would be the class in your project that `implements ClusterItem`. If you could provide the source code for that it would help.
