### ISSUE TITLE
android-map-utils: Crash in ClusterTask

### ISSUE THREAD

**Issue by claudiofelber** [googlemaps/android-maps-utils#660] opened 2020-03-17 13:26 UTC
The ClusterTask doInBackground() method does sometimes crash. It seems that the write lock is released in a different thread than it is being acquired. The internal ReentrantReadWriteLock.tryRelease() method complains that the lock is not being held exclusively. This might have something to do with the fact that the ClusterTask is now running on the thread pool executor.

#### Environment details

Tested with android-map-utils 1.0.0 on Android API 28.

#### Steps to reproduce

Execute the cluster() method repeatedly with lots of items.

#### Stack trace
```
2020-03-17 13:56:31.860 29075-29148/ch.infoflora.florapp.dev E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: ch.infoflora.florapp.dev, PID: 29075
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalMonitorStateException
        at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryRelease(ReentrantReadWriteLock.java:373)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1285)
        at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.unlock(ReentrantReadWriteLock.java:1138)
        at com.google.maps.android.clustering.algo.AbstractAlgorithm.unlock(AbstractAlgorithm.java:37)
        at com.google.maps.android.clustering.ClusterManager$ClusterTask.doInBackground(ClusterManager.java:297)
        at com.google.maps.android.clustering.ClusterManager$ClusterTask.doInBackground(ClusterManager.java:290)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by barbeau** [comment] 2020-03-17 15:04
@claudiofelber Thanks for reporting this! We'll take a look.

**Comment by barbeau** [comment] 2020-03-17 15:12
@claudiofelber This is new to v1.0.0, right? You didn't see this in previous versions?

**Comment by claudiofelber** [comment] 2020-03-17 15:15
Yes, this is the new v1.0.0 release. I did not yet check with one of the previous versions but will do so in a couple of hours.

**Comment by barbeau** [comment] 2020-03-17 15:23
@claudiofelber Ok, thanks. Also, how exactly are you producing this? I can't seem to reproduce it with the demo app.

**Comment by afluong** [comment] 2020-06-11 21:28
Hi, I think I am facing the same issue that causes crashes with the same kind of context.

**Environment details**
Tested with android-map-utils **1.3.1** and android-map-utils **1.3.3**
On several devices 
<img width="376" alt="Capture d’écran 2020-06-11 à 23 16 42" src="https://user-images.githubusercontent.com/15310975/84440067-a59f1100-ac39-11ea-9754-cefb9412964c.png">


**Steps to reproduce**
1. Execute the cluster() method repeatedly with lots of items.
2. If it's not happening on the first launch, kill it and launch it again, the crash happens 1 of 5 kills/launches 

**Stack Trace**
<img width="919" alt="Capture d’écran 2020-06-11 à 22 32 15" src="https://user-images.githubusercontent.com/15310975/84440960-2e6a7c80-ac3b-11ea-83ae-b372288f818f.png">


I don't know if I am doing something wrong, but I just :
- first init algorithm (NonHierarchicalViewBasedAlgorithm) and renderer
- then I got an API call with all lat/lng I want to display on map and call the cluster() method to display them.

If you want me to create another issue regarding this, let me know !

**Comment by barbeau** [comment] 2020-06-11 22:17
@afluong Thanks for the info! Re-opening. Could you provide an example app that reproduces this? I couldn't get it to reproduce with the demo app.

**Comment by afluong** [comment] 2020-06-11 22:28
Hi @barbeau, thanks for the quick response ! 
I assume that you will need the source code ?
Well, it is actually in a "professional" app, so I will see if I can extract all the code that causes issue and send you this.

I go back to you ASAP !

**Comment by barbeau** [comment] 2020-06-11 22:29
If you're able to add the relevant source code to the demo app in this repository, that would be ideal.

**Comment by afluong** [comment] 2020-06-11 22:31
Oh, OK.
I will see that !

**Comment by afluong** [comment] 2020-06-11 23:29
Ok, I forked the repo and push the source code that crashes here : https://github.com/afluong/android-maps-utils
Let me know if it is OK that way.

To reproduce the crash, you will have to open and kill the app a couple of times (at least 4 times).

**Comment by barbeau** [comment] 2020-06-15 14:06
@afluong Thanks! This should help.

**Comment by jeffdgr8** [comment] 2020-07-02 08:56
Fixed in https://github.com/googlemaps/android-maps-utils/pull/761

**Comment by jeffdgr8** [comment] 2020-07-02 09:39
As a workaround to avoid this crash, you can ensure that `ClusterManager.setAlgorithm()` is called before `ClusterManager.setRenderer()`, so the algorithm is set before `cluster()` is called for the first time. Even with the fixed code, it would still be best to set the algorithm before the renderer to avoid clustering with the default algorithm before setting it to your intended implementation.

**Comment by afluong** [comment] 2020-07-02 22:14
@jeffdgr8 Thanks ! 
Noted for the algorithm and renderer, it seems to work well now👌😉

**Closed** 2020-07-07 16:12 UTC
Labels: priority: p1, type: bug
