### ISSUE TITLE
Marker with IconGenerator is not poining to correct position on Android 7.0+

### ISSUE THREAD

**Issue by Kamil-H** [googlemaps/android-maps-utils#342] opened 2016-12-28 10:33 UTC
**Summary:** 

Markers putted with IconGenerator are not pointing to correct positions on Android 7.0+. The problem is getting worse, when I'm zooming out, because the point where the marker is pointing to is getting out of circle.

**Steps to reproduce:** 

Put a marker on map with IconGenerator and then put another marker (standard this time) in the same position. 
Code snippet:
```
private void markPosition(LatLng latLng){
    googleMap.addMarker(new MarkerOptions().position(latLng));
    putWhiteMarkerWithPlusAndRemoveLast(googleMap, locationName, latLng);
}

private void putWhiteMarkerWithPlusAndRemoveLast(GoogleMap googleMap, String locationName, LatLng latLng){
    IconGenerator iconGenerator = new IconGenerator(this);
    iconGenerator.setContentView(getWhiteViewWithPlus(locationName));
}

private View getWhiteViewWithPlus(String locationName){
    View view = ((LayoutInflater) getSystemService(Context.LAYOUT_INFLATER_SERVICE)).inflate(R.layout.marker_white_with_plus, null);
    TextView markerTextView = (TextView) view.findViewById(R.id.markerTextView);
    markerTextView.setText(locationName);
    return view;
}
```
marker_white_with_plus:
```
<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:android="http://schemas.android.com/apk/res/android">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/markerTextView"
        android:textSize="15sp"
        android:gravity="center_vertical"
        android:paddingLeft="8dp"
        android:drawableRight="@drawable/ic_add_marker"
        android:drawableEnd="@drawable/ic_add_marker"
        android:textColor="@color/black"/>
</LinearLayout>
```

**Expected behavior:** 

Both markers pointing to the same position.

**Observed behavior:** 

Standard GoogleMaps marker is pointing to the right position. The IconGenerator marker is pointing to position located on the left from the right position.

**Device and Android version:** 

- **LG Nexus 5X (Stock Android 7.0, 7.1) - bad behavior.**
- HTC One M7 (Cyanogenmod 12.1, Android 5.1.1) correct behavior.
- Samsung Galaxy S7 (TouchWiz, Android 6.0.1) correct behavior.

**Screenshots:** 
In the same order as above:
![nexus_5x_android_7 0](https://cloud.githubusercontent.com/assets/11328102/21519923/e94e3416-ccf0-11e6-9a81-68d30de94fca.jpg)
![htc_one_m7_android_5 1 1](https://cloud.githubusercontent.com/assets/11328102/21519925/e9511c4e-ccf0-11e6-8e4e-b43f5587e9cf.jpg)
![samgung_galaxy_s7_android_6 0 1](https://cloud.githubusercontent.com/assets/11328102/21519924/e94f00e4-ccf0-11e6-9a7a-fab2ee4fdfff.jpg)
(Here the standard marker is hardly visible, but it is there. I uploaded the original size screenshot, here:
http://i.imgur.com/mS2qqJv.jpg)

**Comment by barbeau** [comment] 2016-12-30 03:06
Thanks for the report! Could you please put together a really simple
project on Github that repros this on your 5X?  I'd like to test on another
N device but want to make sure it's the exact same code.

On Dec 28, 2016 5:33 AM, "Kamil-H" <notifications@github.com> wrote:

*Summary:*

Markers putted with IconGenerator are not pointing to correct positions on
Android 7.0+. The problem is getting worse, when I'm zooming out, because
the point where the marker is pointing to is getting out of circle.

*Steps to reproduce:*

Put a marker on map with IconGenerator and then put another marker
(standard this time) in the same position.
Code snippet:

private void markPosition(LatLng latLng){
    googleMap.addMarker(new MarkerOptions().position(latLng));
    putWhiteMarkerWithPlusAndRemoveLast(googleMap, locationName, latLng);
}

private void putWhiteMarkerWithPlusAndRemoveLast(GoogleMap googleMap,
String locationName, LatLng latLng){
    IconGenerator iconGenerator = new IconGenerator(this);
    iconGenerator.setContentView(getWhiteViewWithPlus(locationName));
}

private View getWhiteViewWithPlus(String locationName){
    View view = ((LayoutInflater)
getSystemService(Context.LAYOUT_INFLATER_SERVICE)).inflate(R.layout.marker_white_with_plus,
null);
    TextView markerTextView = (TextView) view.findViewById(R.id.markerTextView);
    markerTextView.setText(locationName);
    return view;
}

marker_white_with_plus:

<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:android="http://schemas.android.com/apk/res/android">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/markerTextView"
        android:textSize="15sp"
        android:gravity="center_vertical"
        android:paddingLeft="8dp"
        android:drawableRight="@drawable/ic_add_marker"
        android:drawableEnd="@drawable/ic_add_marker"
        android:textColor="@color/black"/>
</LinearLayout>

*Expected behavior:*

Both markers pointing to the same position.

*Observed behavior:*

Standard GoogleMaps marker is pointing to the right position. The
IconGenerator marker is pointing to position located on the left from the
right position.

*Device and Android version:*

   - *LG Nexus 5X (Stock Android 7.0, 7.1) - bad behavior.*
   - HTC One M7 (Cyanogenmod 12.1, Android 5.1.1) correct behavior.
   - Samsung Galaxy S7 (TouchWiz, Android 6.0.1) correct behavior.

*Screenshots:*
In the same order as above:
[image: nexus_5x_android_7 0]
<https://cloud.githubusercontent.com/assets/11328102/21519923/e94e3416-ccf0-11e6-9a81-68d30de94fca.jpg>
[image: htc_one_m7_android_5 1 1]
<https://cloud.githubusercontent.com/assets/11328102/21519925/e9511c4e-ccf0-11e6-8e4e-b43f5587e9cf.jpg>
[image: samgung_galaxy_s7_android_6 0 1]
<https://cloud.githubusercontent.com/assets/11328102/21519924/e94f00e4-ccf0-11e6-9a7a-fab2ee4fdfff.jpg>
(Here the standard marker is hardly visible, but it is there. I uploaded
the original size screenshot, here:
http://i.imgur.com/mS2qqJv.jpg)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlemaps/android-maps-utils/issues/342>, or mute the
thread

**Comment by barbeau** [comment] 2016-12-30 03:11
Also, can you please add the currently installed Google Play Services app
version for each of the devices?

On Dec 29, 2016 10:06 PM, "Sean Barbeau" <sjbarbeau@gmail.com> wrote:

Thanks for the report! Could you please put together a really simple
project on Github that repros this on your 5X?  I'd like to test on another
N device but want to make sure it's the exact same code.


On Dec 28, 2016 5:33 AM, "Kamil-H" <notifications@github.com> wrote:

*Summary:*

Markers putted with IconGenerator are not pointing to correct positions on
Android 7.0+. The problem is getting worse, when I'm zooming out, because
the point where the marker is pointing to is getting out of circle.

*Steps to reproduce:*

Put a marker on map with IconGenerator and then put another marker
(standard this time) in the same position.
Code snippet:

private void markPosition(LatLng latLng){
    googleMap.addMarker(new MarkerOptions().position(latLng));
    putWhiteMarkerWithPlusAndRemoveLast(googleMap, locationName, latLng);
}

private void putWhiteMarkerWithPlusAndRemoveLast(GoogleMap googleMap,
String locationName, LatLng latLng){
    IconGenerator iconGenerator = new IconGenerator(this);
    iconGenerator.setContentView(getWhiteViewWithPlus(locationName));
}

private View getWhiteViewWithPlus(String locationName){
    View view = ((LayoutInflater)
getSystemService(Context.LAYOUT_INFLATER_SERVICE)).inflate(R.layout.marker_white_with_plus,
null);
    TextView markerTextView = (TextView) view.findViewById(R.id.markerTextView);
    markerTextView.setText(locationName);
    return view;
}

marker_white_with_plus:

<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:android="http://schemas.android.com/apk/res/android">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/markerTextView"
        android:textSize="15sp"
        android:gravity="center_vertical"
        android:paddingLeft="8dp"
        android:drawableRight="@drawable/ic_add_marker"
        android:drawableEnd="@drawable/ic_add_marker"
        android:textColor="@color/black"/>
</LinearLayout>

*Expected behavior:*

Both markers pointing to the same position.

*Observed behavior:*

Standard GoogleMaps marker is pointing to the right position. The
IconGenerator marker is pointing to position located on the left from the
right position.

*Device and Android version:*

   - *LG Nexus 5X (Stock Android 7.0, 7.1) - bad behavior.*
   - HTC One M7 (Cyanogenmod 12.1, Android 5.1.1) correct behavior.
   - Samsung Galaxy S7 (TouchWiz, Android 6.0.1) correct behavior.

*Screenshots:*
In the same order as above:
[image: nexus_5x_android_7 0]
<https://cloud.githubusercontent.com/assets/11328102/21519923/e94e3416-ccf0-11e6-9a81-68d30de94fca.jpg>
[image: htc_one_m7_android_5 1 1]
<https://cloud.githubusercontent.com/assets/11328102/21519925/e9511c4e-ccf0-11e6-8e4e-b43f5587e9cf.jpg>
[image: samgung_galaxy_s7_android_6 0 1]
<https://cloud.githubusercontent.com/assets/11328102/21519924/e94f00e4-ccf0-11e6-9a7a-fab2ee4fdfff.jpg>
(Here the standard marker is hardly visible, but it is there. I uploaded
the original size screenshot, here:
http://i.imgur.com/mS2qqJv.jpg)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlemaps/android-maps-utils/issues/342>, or mute the
thread

**Comment by Kamil-H** [comment] 2016-12-30 06:06
@barbeau 
Google Play Services versions are:
- LG Nexus 5X - 10.0.84 (440-137749526)
- HTC One M7 - 10.0.84 (238-137749526)
- Samsung Galaxy S7 - 10.0.84 (440-137749526)

I will try to prepare a sample application and as soon I finish it I will post it here.

**Comment by Kamil-H** [comment] 2016-12-30 07:35
@barbeau 
https://github.com/Kamil-H/MarkerErrorSample
Here is a sample application that shows this problem. You can "longClick" on map to change the position of the marker.
Please try to zoom-out and see where both markers are pointing to.

**Comment by barbeau** [comment] 2016-12-30 15:25
Thanks!

**Comment by barbeau** [comment] 2017-01-03 15:09
Interestingly, I can't repro this with https://github.com/Kamil-H/MarkerErrorSample and an LG G5 with Android 7.0 and Google Play services app 10.0.84 (440-137749526):

![image](https://cloud.githubusercontent.com/assets/928045/21611719/05b011e2-d19c-11e6-82fe-a29f152f22e2.png)

I had to change the Google Maps API key in `AndroidManifest.xml` to get the map to show (I used an unrestricted key I just created in the Google API Console), but otherwise the demo app I installed is identical to the one on Github.

Could you please try uninstalling the sample app and Google Maps and clearing the cache for Google Play Services app, turning the device off and back on, reinstall Google Maps and sample app and see if you still see the same problem?

I've seen the cache for Google Play Services app get corrupted before, and maybe that's what is causing this.

**Comment by Kamil-H** [comment] 2017-01-03 19:43
This problem occurs on two completely separated LG Nexus 5X on either 7.0 and 7.1 versions, so maybe here is a problem. I thought this problem is related to newer Android versions, but it seems I was wrong. I will try to test it on different devices especially on other Nexus devices.
Anyway, thank you so much for checking it. I didn't have any other device with Android 7.0+ on hand, so good to know that problem is not here.

**Comment by barbeau** [comment] 2017-01-04 22:02
Thanks @Kamil-H, I'm going to close this out as I don't think it's related to this library.  If you find out what's causing this please let me know!

**Closed by barbeau** 2017-01-04 22:02 UTC

**Comment by jeffreyliu8** [comment] 2017-09-27 18:49
I have the same issue, using latest code from today, but with some minor update:

com.google.android.gms:play-services-maps:11.4.0
compileSdkVersion 26
buildToolsVersion "26.0.1"

This is on google pixel Oreo.

You should be able to tell that the triangle on the bottom part is not in the center.

![test](https://user-images.githubusercontent.com/12398645/30931525-c6a813c2-a379-11e7-89b3-d7e68fbd0446.png)
