### ISSUE TITLE
Crash after updating from version 0.6.2 to 1.1.0

### ISSUE THREAD

**Issue by HermineSan** [googlemaps/android-maps-utils#694] opened 2020-04-15 20:42 UTC
**Environment details**

1. Custom look with NonHierarchicalViewBasedAlgorithm
2. Huawei P20 lite, Android 9
3. android-maps-utils:1.1.0

**Steps to reproduce**
_I have a fab for moving to the current location_

- Press on my location fab
- Go back to the previous screen, before map shows the current location
- Come back to the map screen and press my location fab again.

It's not crashing every time and I'm able to reproduce it only on the mentioned device.

**Stack trace**
java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryRelease ReentrantReadWriteLock.java:373
java.util.concurrent.locks.AbstractQueuedSynchronizer.release AbstractQueuedSynchronizer.java:1285
java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.unlock ReentrantReadWriteLock.java:1138
com.google.maps.android.clustering.algo.AbstractAlgorithm.unlock AbstractAlgorithm.java:37
com.google.maps.android.clustering.ClusterManager$ClusterTask.doInBackground ClusterManager.java:297
com.google.maps.android.clustering.ClusterManager$ClusterTask.doInBackground ClusterManager.java:290
android.os.AsyncTask$2.call AsyncTask.java:334
java.util.concurrent.FutureTask.run FutureTask.java:266
java.util.concurrent.ThreadPoolExecutor.processTask ThreadPoolExecutor.java:1187
java.util.concurrent.ThreadPoolExecutor.runWorker ThreadPoolExecutor.java:1152
java.util.concurrent.ThreadPoolExecutor$Worker.run ThreadPoolExecutor.java:641
java.lang.Thread.run Thread.java:784

android.os.AsyncTask$3.done AsyncTask.java:355
java.util.concurrent.FutureTask.finishCompletion FutureTask.java:383
java.util.concurrent.FutureTask.setException FutureTask.java:252
java.util.concurrent.FutureTask.run FutureTask.java:271
java.util.concurrent.ThreadPoolExecutor.processTask ThreadPoolExecutor.java:1187
java.util.concurrent.ThreadPoolExecutor.runWorker ThreadPoolExecutor.java:1152
java.util.concurrent.ThreadPoolExecutor$Worker.run ThreadPoolExecutor.java:641
java.lang.Thread.run Thread.java:784

**Comment by barbeau** [comment] 2020-06-22 14:21
@HermineSan Thanks for reporting this! Looks like this is a duplicate of https://github.com/googlemaps/android-maps-utils/issues/660, so I'm going to close this so the discussion can continue at https://github.com/googlemaps/android-maps-utils/issues/660.

**Closed by barbeau** 2020-06-22 14:21 UTC
Labels: triage me, type: bug
