### ISSUE TITLE
Removing KML Layer is not working

### ISSUE THREAD

**Issue by OnyuPodo** [googlemaps/android-maps-utils#538] opened 2019-09-04 05:54 UTC
Hi, I have some problems with removing KML Layer from Google Map Android.
when I add it to a map using KmlLayer it works well, but when I try to remove the layer nothing is removed.

**Steps to reproduce:** 
- Open a KML file and create a KmlLayer with it.
- call addLayerToMap() method
- call removeLayerFromMap() method (nothing happened)

**Expected behavior:** 

The layer is removed from the map

**Observed behavior:** 

The layer is not removed.

**Comment by imunique-ZJ** [comment] 2020-01-21 01:59
Same here. I have to call `map.clear()` which will remove all layers and markers.

**Comment by barbeau** [comment] 2020-01-21 14:58
@OnyuPodo @imunique-ZJ I can't reproduce this with the current master branch version of the library and the `KmlDemoActivity` in this library. In `KmlDemoActivity.onPostExecute()`, if I add the line to remove the layer after it's added the layer is correctly removed (you can't see the Google building polygons on the map):

~~~
                KmlLayer kmlLayer = new KmlLayer(mMap, new ByteArrayInputStream(byteArr),
                        KmlDemoActivity.this);
                kmlLayer.addLayerToMap();
                kmlLayer.setOnFeatureClickListener(new KmlLayer.OnFeatureClickListener() {
                    @Override
                    public void onFeatureClick(Feature feature) {
                        Toast.makeText(KmlDemoActivity.this,
                                "Feature clicked: " + feature.getId(),
                                Toast.LENGTH_SHORT).show();
                    }
                });
                moveCameraToKml(kmlLayer);
                kmlLayer.removeLayerFromMap();
~~~

What version of the library do you see this in? And can you provide a more complete example (including KML file and code) that reproduces this (ideally based on the `KmlDemoActivity`)?

**Comment by imunique-ZJ** [comment] 2020-01-22 00:16
Maybe it's the `MultiGeometry` to blame.
I am using v0.6.2, and the following is what I found:

KmlRenderer.java
```
public void removeLayerFromMap() {
    this.removePlacemarks(this.getAllFeatures());
    ...
}
private void removePlacemarks(HashMap<? extends Feature, Object> placemarks) {
    removeFeatures(placemarks);
}
```

Renderer.java
```
protected static void removeFeatures(HashMap<Feature, Object> features) {
    Iterator var1 = features.values().iterator();

    while(var1.hasNext()) {
        Object mapObject = var1.next();
        if (mapObject instanceof Marker) {
            ((Marker)mapObject).remove();
        } else if (mapObject instanceof Polyline) {
            ((Polyline)mapObject).remove();
        } else if (mapObject instanceof Polygon) {
            ((Polygon)mapObject).remove();
        }
        // here, I got ArrayList<Polyline>, but it was ignored
    }
}
```

Since `removeFeatures ` doesn't remove list of `Polyline`s, the routes on the map are not removed. However, another method `removeFromMap` does.
```
public static void removeFromMap(Object mapObject) {
    if (mapObject instanceof Marker) {
        ((Marker)mapObject).remove();
    } else if (mapObject instanceof Polyline) {
        ((Polyline)mapObject).remove();
    } else if (mapObject instanceof Polygon) {
        ((Polygon)mapObject).remove();
    } else if (mapObject instanceof ArrayList) { // here, it will remove objects in the list
        Iterator var1 = ((ArrayList)mapObject).iterator();

        while(var1.hasNext()) {
            Object mapObjectElement = var1.next();
            removeFromMap(mapObjectElement);
        }
    }
}
```
So, I create a workaround solution like previous post.
Here's my kml
[tw_bike_cycling_1_1.zip](https://github.com/googlemaps/android-maps-utils/files/4094504/1-1.zip)

Hope it helps you.

**Comment by barbeau** [comment] 2020-01-22 15:01
Thanks @imunique-ZJ! That definitely helps. I can confirm the bug in the current master branch with the KML you provided - I've tested within the `KmlDemoActivity` here:
https://github.com/CUTR-at-USF/android-maps-utils/tree/test-kml-remove

The line within the multigeometry remains on the map after calling `kmlLayer.removeLayerFromMap();`:

![image](https://user-images.githubusercontent.com/928045/72905178-1b8ff380-3cfe-11ea-8fab-9556331323e8.png)

**Comment by barbeau** [comment] 2020-01-24 15:50
Looks like this issue is fixed in https://github.com/googlemaps/android-maps-utils/pull/380

**Comment by imunique-ZJ** [comment] 2020-01-25 00:01
Yes, looks the changes take care of Collection. But how do I test with the PR?

**Comment by barbeau** [comment] 2020-01-25 02:42
It should hopefully be merged soon. Or you can check out the PR and test yourself, which is what I did:

~~~
git checkout -b jeffdgr8-kml-marker-manager master
git pull https://github.com/jeffdgr8/android-maps-utils.git kml-marker-manager
~~~

**Closed** 2020-01-28 14:44 UTC
Labels: priority: p2, type: bug
