### ISSUE TITLE
ClusterManager draws markers in invisible regions

### ISSUE THREAD

**Issue by kaads123** [googlemaps/android-maps-utils#404] opened 2017-06-28 15:18 UTC
**Summary:** 

ClusterManager draws all the markers/clusters, not only visible ones. It should draw only those that are in visibleRegion. This causes a map with 2000 markers skip frames and ANR (even on new devices) when zooming in/out.

**Steps to reproduce:** 

Add 2000 or more markers and try zooming in and zooming out fast. This can be reproduced in the sample app

**Expected behavior:** 

Draw only those markers/clusters which are in visibleRegion.latLngBounds of the GoogleMap

**Observed behavior:** 

Draws every marker added to ClusterManager

**Device and Android version:** 

Moto G3 with Android 6.0.1
Nexus 6P with Android 7.1.2

**Screenshots:** 

![screenshot_20170628-182053](https://user-images.githubusercontent.com/13378420/27645450-c47d1f4e-5c2e-11e7-9b33-8a9e2907e6b8.png)

Zoomed out from 20f to 1f quickly

**Comment by zamesilyasa** [comment] 2017-06-30 08:34
@kaads123 
Looks like duplicate of https://github.com/googlemaps/android-maps-utils/issues/82

**Comment by kaads123** [comment] 2017-06-30 13:22
@zamesilyasa You're right, what should I do with this one?

**Comment by barbeau** [comment] 2017-06-30 13:35
Closing as a duplicate of https://github.com/googlemaps/android-maps-utils/issues/82.  

@kaads123 Thanks for the steps to reproduce and screenshot - I'll copy these over to #82 so we don't lose them.

**Closed by barbeau** 2017-06-30 13:35 UTC
Labels: duplicate
