### ISSUE TITLE
RemoveLayerFromMap() not working

### ISSUE THREAD

**Issue by achercasky** [googlemaps/android-maps-utils#270] opened 2016-04-10 17:48 UTC
Hi everyone!

I'm trying to remove the kml layer using this method.. **layer.removeLayerFromMap();** and nothing happens.

The only way to remove the kml is to clear the map but that's not the correct way because I'm using more than one kml.

Any idea or solution?

Thanks!

**Comment by stephenmcd** [comment] 2016-06-30 03:19
I've successfully removed layers one by one calling `layer. removeLayerFromMap()`.

If you can upload a reproducible example somewhere, someone might be able to help you.

I'll close this for now though since it doesn't seem to be an issue.

**Closed by stephenmcd** 2016-06-30 03:19 UTC

**Comment by paamand** [comment] 2017-07-31 20:58
I can confirm that this is an issue. layer.removeLayerFromMap() clears placemarks but does not clear polylines.
